# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160418_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='checking_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='saving_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='card_num',
            field=models.CharField(default='9459293572301075', max_length=16),
        ),
    ]
