# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160418_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_num',
            field=models.CharField(default='1555363332285110', max_length=16),
        ),
    ]
